<a href="https://colab.research.google.com/github/karthikravi123/genai_samples/blob/main/vectorDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###FAISS - TIs is an open source library developed by facebook AI research well desgined for
##efficient similarity search for dense vectors(sentence embedding and image embedding in high vector space)
## like (1,000,00 +) high dimension vectors

##most similarity vector - this is what FAISS is built for




In [63]:
# !pip install faiss-cpu

In [64]:
import faiss
#facebook ai similarity search

In [17]:
# !pip install sentence-transformers

In [18]:

import numpy as np
from sentence_transformers import SentenceTransformer  ##turning text intoembedding
##transormer based from huggung face
#model used for embedding

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(


In [19]:
model = SentenceTransformer("all-MIniLM-L6-v2")
print(model)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)


In [67]:
documents = ['The cat is ont he mat',
             'Dog is mans good friend',
             'The quick brown fox jumps',
             'i love playing football every weekend'
             ]

print(documents)

['The cat is ont he mat', 'Dog is mans good friend', 'The quick brown fox jumps', 'i love playing football every weekend']


In [68]:
embeddings = model.encode(documents,show_progress_bar=True)
embeddings

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

array([[ 0.08834062,  0.01553085, -0.0035006 , ...,  0.00601809,
         0.0158007 ,  0.06285997],
       [-0.06701512, -0.05370077,  0.03138087, ...,  0.04591466,
         0.00511143,  0.03238372],
       [ 0.02984706,  0.00575639,  0.02885567, ...,  0.00129805,
         0.0086353 ,  0.04905399],
       [ 0.00416546, -0.05110833,  0.02057043, ...,  0.00714686,
        -0.00811256, -0.05875878]], dtype=float32)

In [69]:
embeddings[0]

array([ 8.83406177e-02,  1.55308470e-02, -3.50059802e-03,  2.25460287e-02,
       -5.20943515e-02,  2.82273889e-02,  7.90146068e-02,  4.49392237e-02,
       -2.95137633e-02,  1.35609256e-02,  3.59956105e-03, -5.48815820e-03,
       -1.33762881e-02,  6.91520795e-02, -4.02798653e-02, -3.28616686e-02,
       -6.79595247e-02,  5.32280887e-03,  5.33757694e-02, -2.46875640e-03,
        3.60588706e-03,  1.94209442e-02,  2.92993467e-02, -6.40375018e-02,
       -1.01392500e-01,  6.05045557e-02, -3.96262631e-02, -6.11051470e-02,
        5.39807938e-02, -8.49874504e-03, -3.73099670e-02,  1.15111079e-02,
       -1.43887959e-02,  3.24010104e-02, -5.79768158e-02, -7.65440091e-02,
       -4.88716085e-03, -2.22179480e-02,  3.49750072e-02,  9.49796066e-02,
        3.37554328e-02, -1.45220878e-02, -2.83210333e-02, -4.11187448e-02,
        1.40164746e-02,  1.97428111e-02,  8.77757221e-02, -1.29589796e-01,
        6.09520040e-02, -1.94177292e-02, -8.36375281e-02,  4.04450074e-02,
        7.01941103e-02, -

In [70]:
#faiss index creation
#convert the embedding tp float32

embeddings_np = np.array(embeddings).astype("float32")
embeddings_np

array([[ 0.08834062,  0.01553085, -0.0035006 , ...,  0.00601809,
         0.0158007 ,  0.06285997],
       [-0.06701512, -0.05370077,  0.03138087, ...,  0.04591466,
         0.00511143,  0.03238372],
       [ 0.02984706,  0.00575639,  0.02885567, ...,  0.00129805,
         0.0086353 ,  0.04905399],
       [ 0.00416546, -0.05110833,  0.02057043, ...,  0.00714686,
        -0.00811256, -0.05875878]], dtype=float32)

In [71]:
embeddings_np.shape

(4, 384)

In [72]:
embeddings_np.shape[1]

384

In [73]:
#create index
dimension = embeddings_np.shape[1]
dimension

384

In [74]:
index = faiss.IndexFlatL2(dimension)

In [75]:
##add embeddings to index
index.add(embeddings_np)
print("Faiss index size -",index.ntotal)

Faiss index size - 4


In [76]:
###searching similar items
query = "I enjoy playing soccer"

query_vector = model.encode([query]).astype('float32')
print(query_vector)

[[ 4.87698521e-03 -5.30442968e-03 -2.75011696e-02  1.84032265e-02
   4.96961884e-02  1.79405585e-02  1.10318117e-01  4.86721285e-02
   1.00387342e-01  8.59604776e-02 -2.06266847e-02 -5.78926019e-02
  -2.57253796e-02  8.81209522e-02  1.02164529e-01 -2.09649503e-02
  -7.10202307e-02 -2.73457225e-02 -2.03812458e-02 -5.69095872e-02
  -8.28627571e-02  2.04674434e-02  2.49739140e-02 -5.10388007e-03
  -6.45004436e-02  1.85866505e-02  1.62095446e-02  4.90282923e-02
  -2.71630920e-02 -6.43082708e-02 -6.93926439e-02  6.40530586e-02
   6.96975142e-02  3.78047153e-02 -5.55525608e-02  6.43912107e-02
   1.02673784e-01 -5.75676113e-02  1.06815528e-02  4.43639345e-02
   2.53020544e-02 -2.74827126e-02  6.35689571e-02  9.15494002e-03
  -1.67886410e-02  7.24386945e-02  5.43722436e-02 -2.26804111e-02
   5.26077151e-02  4.83293459e-02  6.17992617e-02  9.27435458e-02
  -7.51541834e-03 -1.57831796e-02  5.75741008e-02  6.05144016e-02
   5.32954582e-04  2.75647156e-02 -1.70828514e-02 -5.01391143e-02
   5.73507

In [77]:
print(len(query_vector))

1


In [78]:
##number of nearest neighbours (k)

k = 3
distances,indices = index.search(query_vector,k)
print("top 3 results")
for i in indices[0]:
  print(documents[i])

top 3 results
i love playing football every weekend
Dog is mans good friend
The quick brown fox jumps


In [79]:
print(indices)
print(distances)

[[3 1 2]]
[[0.6799574 1.7265373 1.8744137]]


In [80]:
##save the index
faiss.write_index(index,'faiss_index.index')

In [81]:
#load the index
loaded_index = faiss.read_index('faiss_index.index')
loaded_index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7d77958a4720> >

In [84]:
query = ["can you tell me story of animals",
         "tell me about dogs"]

query_vector = model.encode(query).astype('float32')


In [85]:
k = 2
distances,indices = index.search(query_vector,k)

for i , q in enumerate(query):
  print(q)
  for idx in indices[i]:
    print(documents[idx])
  print("===")

can you tell me story of animals
Dog is mans good friend
The quick brown fox jumps
===
tell me about dogs
Dog is mans good friend
The quick brown fox jumps
===


In [3]:
# !pip install chromadb

In [2]:
import chromadb

In [8]:
client = chromadb.Client()

In [9]:
collection = client.get_or_create_collection(name="my_documents")
collection

Collection(name=my_documents)

In [10]:
documents = ['The cat is ont he mat',
             'Dog is mans good friend',
             'The quick brown fox jumps',
             'i love playing football every weekend'
             ]


In [20]:
embeddings = model.encode(documents,show_progress_bar=True)
embeddings

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

array([[ 0.08834063,  0.0155308 , -0.00350058, ...,  0.00601806,
         0.01580067,  0.06286   ],
       [-0.0670151 , -0.05370072,  0.03138088, ...,  0.04591462,
         0.00511146,  0.03238376],
       [ 0.02984713,  0.00575643,  0.02885566, ...,  0.00129802,
         0.00863532,  0.049054  ],
       [ 0.00416546, -0.05110836,  0.0205705 , ...,  0.00714683,
        -0.00811266, -0.05875876]], dtype=float32)

In [21]:
###adding the documents in my collections
collection.add(documents=documents,
               ids = [str(i) for i in range(len(documents))],embeddings=embeddings.tolist())

In [22]:
query = "i like to play soccer"
query_embedding = model.encode([query]).tolist()

results = collection.query(query_embeddings=query_embedding,n_results=2)
results

{'ids': [['3', '1']],
 'embeddings': None,
 'documents': [['i love playing football every weekend',
   'Dog is mans good friend']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None]],
 'distances': [[0.7478294372558594, 1.7153356075286865]]}